---
- name: Create dns zone
  openstack.cloud.dns_zone:
    cloud: "{{ cloud }}"
    name: "{{ dns_zone_name }}"
    zone_type: "primary"
    email: test@example.net
  register: dns_zone

- debug: var=dns_zone

- name: Update dns zone
  openstack.cloud.dns_zone:
    cloud: "{{ cloud }}"
    name: "{{ dns_zone.zone.name }}"
    description: "New descirption"
  register: updated_dns_zone

- debug: var=updated_dns_zone

- name: Delete dns zone
  openstack.cloud.dns_zone:
    cloud: "{{ cloud }}"
    name: "{{ updated_dns_zone.zone.name }}"
    state: absent
  register: deleted_dns_zone

- name: Verify dns zone
  assert:
    that:
    - deleted_dns_zone is successful
    - deleted_dns_zone is changed
